apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudpioneer-agent
spec:
  selector:
    matchLabels:
      name: cloudpioneer-agent
  template:
    metadata:
      labels:
        name: cloudpioneer-agent
    spec:
      containers:
      - name: cloudpioneer-agent
        image: your-docker-image
        ports:
        - containerPort: 8000
