name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  validate:
    name: Validation and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio

      - name: Disable TensorFlow Warnings
        run: |
          export TF_CPP_MIN_LOG_LEVEL=3

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=./ --cov-report=xml --junitxml=test-results.xml

      - name: Ensure artifact files exist
        run: |
          touch test-results.xml coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results.xml
            coverage.xml


            